export const COUNTRY_CITY_OPTIONS = {
  "Kosovë": [
    "Prishtinë",
    "Pejë",
    "Prizren",
    "Gjakovë",
    "Ferizaj",
    "Gjilan",
    "Mitrovicë",
    "Vushtrri",
    "Podujevë",
    "Suharekë",
    "Rahovec",
    "Malishevë",
    "Klinë",
    "Istog",
    "Deçan",
    "Fushë Kosovë",
    "Lipjan",
    "Drenas",
  ],
  "Shqipëri": [
    "Tiranë",
    "Durrës",
    "Vlorë",
    "Shkodër",
    "Elbasan",
    "Fier",
    "Korçë",
    "Berat",
    "Sarandë",
    "Gjirokastër",
    "Kukës",
    "Lezhë",
    "Pogradec",
    "Kavajë",
    "Lushnjë",
  ],
  "Maqedoni": [
    "Shkup",
    "Tetovë",
    "Gostivar",
    "Kumanovë",
    "Strugë",
    "Ohër",
    "Dibër",
    "Kërçovë",
    "Manastir",
    "Prilep",
    "Veles",
  ],
  "Mal të Zi": [
    "Podgoricë",
    "Ulqin",
    "Tivar",
    "Budvë",
    "Kotor",
    "Herceg Novi",
    "Nikshiq",
    "Rozhajë",
    "Plavë",
    "Guci",
    "Tuz",
  ],
} as const;

export type CountryName = keyof typeof COUNTRY_CITY_OPTIONS;