export const COUNTRY_CITY_OPTIONS = {
"Kosovë": [
  "Prishtinë",
  "Prizren",
  "Ferizaj",
  "Gjilan",
  "Pejë",
  "Gjakovë",
  "Podujevë",
  "Mitrovicë",
  "Fushë Kosovë",
  "Lipjan",
  "Drenas",
  "Suharekë",
  "Malishevë",
  "Rahovec",
  "Skenderaj",
  "Viti",
  "Istog",
  "Klinë",
  "Vushtrri",
  "Kaçanik",
  "Dragash",
  "Shtime",
  "Obiliq",
  "Kamenicë",
  "Deçan",
  "Leposaviq",
  "Zubin Potok",
  "Zveçan",
  "Novobërdë",
  "Shtërpcë",
  "Graçanicë",
  "Hani i Elezit",
  "Junik",
  "Mamushë",
  "Kllokot",
  "Ranillug",
  "Partesh",
  "Mitrovicë e Veriut",
],
  "Shqipëri": [
    "Tiranë",
    "Durrës",
    "Vlorë",
    "Shkodër",
    "Elbasan",
    "Fier",
    "Korçë",
    "Berat",
    "Sarandë",
    "Gjirokastër",
    "Kukës",
    "Lezhë",
    "Pogradec",
    "Kavajë",
    "Lushnjë",
  ],
  "Maqedoni": [
    "Shkup",
    "Tetovë",
    "Gostivar",
    "Kumanovë",
    "Strugë",
    "Ohër",
    "Dibër",
    "Kërçovë",
    "Manastir",
    "Prilep",
    "Veles",
  ],
  "Mal të Zi": [
    "Podgoricë",
    "Ulqin",
    "Tivar",
    "Budvë",
    "Kotor",
    "Herceg Novi",
    "Nikshiq",
    "Rozhajë",
    "Plavë",
    "Guci",
    "Tuz",
  ],
} as const;

export type CountryName = keyof typeof COUNTRY_CITY_OPTIONS;